backend:
  name: git-gateway
  # name: test-repo

# publish_mode: editorial_workflow
media_folder: cms/assets
public_folder: assets

collections:
  - name: concerts
    label: Concerts
    folder: cms/concerts
    create: true
    fields:
      - { name: title, label: Title, widget: string, required: true }
      - { name: datetime, label: Time, widget: datetime, required: true }
      - { name: path, label: URL Extension, widget: string, required: true }
      - { name: ticketLink, label: Ticket Link, widget: string }
      - { name: locationTitle, label: Location Title, widget: string, required: true }
      - { name: address1, label: Address Line 1, widget: string }
      - { name: address2, label: Address Line 2, widget: string }
      - {
          name: landscapeImage,
          label: Landscape Image,
          widget: image
        }
      - {
          name: portraitImage,
          label: Portrait Image,
          widget: image
        }
      - name: artists
        label: Artists
        widget: "list"
        fields:
          - label: Name
            name: name
            widget: "string"
            required: true
          - label: Instrument
            name: instrument
            widget: string
      - name: programItems
        label: "Program Items (Must make title & composer \"TBA\" unless listing items)"
        widget: "list"
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Composer
            name: composer
            widget: "string"
            required: true
      - name: sponsors
        label: Sponsors
        widget: "list"
        fields:
          - { name: title, label: Title, widget: string, required: true }
          - { name: logo, label: Logo, widget: image, required: true }
      - name: programNotes
        label: "Program Notes"
        widget: "markdown"
