backend:
  name: git-gateway
  # name: test-repo

# publish_mode: editorial_workflow
media_folder: cms/assets
public_folder: assets

collections:
  - name: locations
    label: Locations
    folder: cms/locations
    create: true
    fields:
      - { name: title, label: Title, widget: string, required: true }
      - { name: google_maps_location, label: Google Maps Iframe Src, widget: string }
      - { name: address1, label: Address Line 1, widget: string }
      - { name: address2, label: Address Line 2, widget: string }
  - name: concerts
    label: Concerts
    folder: cms/concerts
    create: true
    fields:
      - { name: title, label: Title, widget: string, required: true }
      - { name: datetime, label: Time, widget: datetime, required: true }
      - {
          name: location,
          label: Location,
          widget: relation,
          collection: locations,
          multiple: false,
          searchFields: ['title'],
          displayFields: ['title'],
          valueField: 'title',
          required: true
        }
      - {
          name: landscapeImage,
          label: Landscape Image,
          widget: image
        }
      - {
          name: portraitImage,
          label: Portrait Image,
          widget: image
        }
      - name: artists
        label: Artists
        widget: "list"
        fields:
          - label: Name
            name: name
            widget: "string"
            required: true
          - label: Instrument
            name: instrument
            widget: string


      # - {
      #     name: program_items,
      #     label: "Program Items",
      #     widget: "list"
      #     fields:
      #       - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
      #   }
      #     fields:
      #       - { label: 'title', name: 'Title', widget: 'string', required: true }
      #       # - { label: composer, name: Composer, widget: string, required: true }
      #   }
