backend:
  name: github
  repo: mylesgearon/salon_21

media_folder: static/assets
public_folder: assets

collections:
  - name: concert
    label: Concert
    folder: cms/concerts
    create: true
    fields:
      - { name: title, label: Title, widget: string, required: true }
      - { name: datetime, label: Time, widget: datetime, required: true }
      - {
          name: artists,
          label: Artists,
          widget: relation,
          collection: artists,
          multiple: true,
          searchFields: ["title"],
          required: true,
        }
  - name: artist
    label: Artist
    folder: cms/artists
    create: true
    fields:
      - { name: title, label: Title, widget: string, required: true }
